# Generated by Django 3.1.7 on 2021-04-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teal', '0002_studyplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Name')),
                ('start_year', models.IntegerField(verbose_name='start_year')),
                ('number_of_students', models.IntegerField(verbose_name='number_of_students')),
                ('language', models.IntegerField(choices=[(1, 'Română'), (2, 'Rusă'), (3, 'Engleză'), (4, 'Franceză')], verbose_name='language')),
                ('form_of_study', models.IntegerField(choices=[(1, 'la zi'), (2, 'la frecvență')], verbose_name='language')),
                ('fantom', models.JSONField()),
                ('id_study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teal.studyplans', verbose_name='id_study_plan')),
                ('study_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teal.studyyear', verbose_name='study_year_id')),
            ],
        ),
    ]
