# Generated by Django 3.1.7 on 2021-04-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teal', '0003_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(db_index=True, max_length=128, verbose_name='faculty')),
                ('form_of_study', models.IntegerField(choices=[(1, 'la zi'), (2, 'la frecvență')], verbose_name='language')),
                ('status', models.IntegerField(choices=[(1, 'Nu este verificat'), (2, 'Verificat')], verbose_name='language')),
                ('groupings', models.JSONField()),
                ('study_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teal.studyyear', verbose_name='study_year_id')),
            ],
        ),
    ]
